server:
    pott: 8080
    
spring:
  datasource:
     url: jdbc:mysql://127.0.0.1/hy_sheji?serverTimezone=UTC&CharacterEncoding=UTF-8
     username: root
     password: a
     driver-class-name: com.mysql.jdbc.Driver
     #SpringBoot返回date日期格式化，解决返回为TIMESTAMP时间戳格式或8小时时间差
  jackson:    
     date-format:   yyyy-MM-dd HH:mm:ss
     time-zone:   GMT+8   
#文件上传
  servlet:
    multipart:
      max-file-size: 7MB  # 单个文件最大值
      max-request-size: 14MB  # 总上传文件最大和值
      enabled: true 
      
logging: 
  level:  
    com: 
     hy:
      sheji: debug
         
mybatis:  #驼峰命名法配置
    configuration:
       mapUnderscoreToCamelCase: true

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  
    

